'\" t
.\" (The preceding line is a note to broken versions of man to tell
.\" them to pre-process this man page with tbl)
.\" Man page for lockrun.
.TH LOCKRUN 1 "24 Jul 2013" "Linux" "Linux User's Manual"
.SH "NAME"
.sp
lockrun \- creates a lockfile

.SH "SYNOPSIS"
.sp
lockrun [\-Q|--quiet] [\-L lockfile-location ] -- <command> <args>


.SH "DESCRIPTION"
.sp
Lockrun makes sure that the given command is executed only when the specified lockfile is not set.
.SH "OPTIONS"

.PP
\-\-help,
.RS 4
Show brief help listing
.RE
.PP
\-\-version,
.RS 4
Report version info
.RE
.PP
\-\-,
.RS 4
Marks end of lockrun options; command and args follow
.RE
.PP
\-\-verbose, \-V
.RS 4
Show more runtime debugging
.pp
\-\-quiet, \-q
.rs4
Exit quietly (and with success) if locked
.pp
\-\-itempotent, \-I
.rs4
See \-\-quiet
.RE
.PP
\-\-lockfile=F, \-L=F
.RS 4
Specify lockfile as file F
.RE
.PP
\-\-wait, \-w
.RS 4
Wait for lockfile to appear (else exit on lock)
.sp
Options with \-\-wait:
.RE
.PP
\-\-sleep=T, \-S=T
.RS 4
Sleep for T seconds on each wait loop
.RE
.PP
\-\-retries=N, \-r=N
.RS 4
Attempt N retries in each wait loop
.RE
.PP
\-\-maxtime=T,
.RS 4
Wait for at most T seconds for a lock, then exit
